using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VehiclePartsManagementSystem.Infrastructure.Migrations
{
    /// <summary>
    /// Aligns Invoices, Sales, Parts, and SaleItems columns with EF entities on legacy databases.
    /// </summary>
    public partial class AlignInvoiceSalesPartsSchema : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Parts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL DEFAULT '',
                    "Description" text NOT NULL DEFAULT '',
                    "Price" numeric NOT NULL DEFAULT 0,
                    "Quantity" integer NOT NULL DEFAULT 0,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "VendorId" integer NULL,
                    CONSTRAINT "PK_Parts" PRIMARY KEY ("Id")
                );

                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "Name" text NOT NULL DEFAULT '';
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "Description" text NOT NULL DEFAULT '';
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "Quantity" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "VendorId" integer NULL;

                DO $$
                BEGIN
                  IF EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = 'Invoices'
                  ) THEN
                    IF EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_schema = 'public' AND table_name = 'Invoices' AND column_name = 'CreatedAt'
                    ) AND NOT EXISTS (
                      SELECT 1 FROM information_schema.columns
                      WHERE table_schema = 'public' AND table_name = 'Invoices' AND column_name = 'CreatedDate'
                    ) THEN
                      ALTER TABLE "Invoices" RENAME COLUMN "CreatedAt" TO "CreatedDate";
                    END IF;
                  END IF;
                END $$;

                CREATE TABLE IF NOT EXISTS "Invoices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "SaleId" integer NOT NULL,
                    "InvoiceNumber" text NOT NULL DEFAULT '',
                    "CreatedDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "IsSent" boolean NOT NULL DEFAULT false,
                    "SentDate" timestamp with time zone NULL,
                    "IsPaid" boolean NOT NULL DEFAULT false,
                    "ReminderSentCount" integer NOT NULL DEFAULT 0,
                    "LastReminderDate" timestamp with time zone NULL,
                    "PaymentStatus" text NOT NULL DEFAULT 'Credit',
                    "DueDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                    "PaidAmount" numeric NOT NULL DEFAULT 0,
                    "BalanceAmount" numeric NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id")
                );

                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "SaleId" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "InvoiceNumber" text NOT NULL DEFAULT '';
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "CreatedDate" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "IsSent" boolean NOT NULL DEFAULT false;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "SentDate" timestamp with time zone NULL;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "IsPaid" boolean NOT NULL DEFAULT false;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "ReminderSentCount" integer NOT NULL DEFAULT 0;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "LastReminderDate" timestamp with time zone NULL;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PaymentStatus" text NOT NULL DEFAULT 'Credit';
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "DueDate" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PaidAmount" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "BalanceAmount" numeric NOT NULL DEFAULT 0;

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_InvoiceNumber" ON "Invoices" ("InvoiceNumber");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Invoices_SaleId" ON "Invoices" ("SaleId");

                ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "Date" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "OriginalTotalAmount" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "TotalAmount" numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Sales" ADD COLUMN IF NOT EXISTS "CustomerId" integer NULL;

                CREATE TABLE IF NOT EXISTS "SaleItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "SaleId" integer NOT NULL,
                    "PartId" integer NOT NULL,
                    "Quantity" integer NOT NULL,
                    "Price" numeric NOT NULL DEFAULT 0,
                    CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id")
                );

                ALTER TABLE "SaleItems" ADD COLUMN IF NOT EXISTS "Price" numeric NOT NULL DEFAULT 0;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Legacy alignment migration — no down.
        }
    }
}
