using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VehiclePartsManagementSystem.Infrastructure.Migrations
{
    public partial class InventoryNotifications : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "Parts" ADD COLUMN IF NOT EXISTS "CriticalStockLevel" integer NOT NULL DEFAULT 3;

                CREATE TABLE IF NOT EXISTS "InventoryNotifications" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PartId" integer NOT NULL,
                    "Message" text NOT NULL DEFAULT '',
                    "Severity" text NOT NULL DEFAULT 'Warning',
                    "IsRead" boolean NOT NULL DEFAULT false,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_InventoryNotifications" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_InventoryNotifications_Parts_PartId" FOREIGN KEY ("PartId")
                        REFERENCES "Parts" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_InventoryNotifications_PartId_IsRead"
                    ON "InventoryNotifications" ("PartId", "IsRead");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "InventoryNotifications";
                ALTER TABLE "Parts" DROP COLUMN IF EXISTS "CriticalStockLevel";
                """);
        }
    }
}
