using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VehiclePartsManagementSystem.Infrastructure.Migrations
{
    /// <summary>
    /// Creates PurchaseInvoices and PurchaseItems when missing (schema was in model snapshot but never migrated).
    /// </summary>
    public partial class EnsurePurchaseTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "PurchaseInvoices" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "VendorName" text NOT NULL,
                    "Date" timestamp with time zone NOT NULL,
                    "TotalAmount" numeric NOT NULL,
                    "VendorId" integer NULL,
                    CONSTRAINT "PK_PurchaseInvoices" PRIMARY KEY ("Id")
                );

                ALTER TABLE "PurchaseInvoices" ADD COLUMN IF NOT EXISTS "VendorId" integer NULL;

                CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoices_VendorId" ON "PurchaseInvoices" ("VendorId");

                CREATE TABLE IF NOT EXISTS "PurchaseItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PurchaseInvoiceId" integer NOT NULL,
                    "PartId" integer NOT NULL,
                    "Quantity" integer NOT NULL,
                    "Price" numeric NOT NULL,
                    CONSTRAINT "PK_PurchaseItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PurchaseItems_PurchaseInvoices_PurchaseInvoiceId"
                        FOREIGN KEY ("PurchaseInvoiceId") REFERENCES "PurchaseInvoices" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PurchaseItems_Parts_PartId"
                        FOREIGN KEY ("PartId") REFERENCES "Parts" ("Id") ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS "IX_PurchaseItems_PurchaseInvoiceId" ON "PurchaseItems" ("PurchaseInvoiceId");
                CREATE INDEX IF NOT EXISTS "IX_PurchaseItems_PartId" ON "PurchaseItems" ("PartId");

                DO $$
                BEGIN
                  IF EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_name = 'Vendors'
                  ) AND NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'FK_PurchaseInvoices_Vendors_VendorId'
                  ) THEN
                    ALTER TABLE "PurchaseInvoices"
                      ADD CONSTRAINT "FK_PurchaseInvoices_Vendors_VendorId"
                      FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT;
                  END IF;
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP TABLE IF EXISTS "PurchaseItems";
                DROP TABLE IF EXISTS "PurchaseInvoices";
                """);
        }
    }
}
