import type { AdminPageId } from '../admin/adminPages'

export const ADMIN_PAGE_LABELS: Record<AdminPageId, string> = {
  home: 'Home',
  'staff-dashboard': 'Staff Dashboard',
  'admin-dashboard': 'Admin Dashboard',
  'staff-management': 'Staff Management',
  customers: 'Manage Customers',
  'search-sale': 'Search & Sale',
  'register-customer': 'Register Customer',
  'sales-history': 'Sales History',
  'credit-management': 'Credit Management',
  'customer-reports': 'Customer Reports',
  'generate-invoice': 'Generate Invoice',
  inventory: 'Manage Parts',
  'create-part': 'Create Part',
  'low-stock-notifications': 'Low Stock Alerts',
  vendors: 'Manage Vendors',
  'create-vendor': 'Create Vendor',
  purchases: 'Purchase Invoices',
  'create-purchase-invoice': 'Create Purchase Invoice',
  'financial-reports': 'Financial Reports',
  'daily-performance-report': 'Daily Performance Report',
  'monthly-performance-report': 'Monthly Performance Report',
  'monthly-top-selling-parts': 'Top Selling Parts',
  'annual-strategic-review': 'Annual Strategic Review',
  appointments: 'Appointments',
  'part-requests': 'Part Requests',
  'community-reviews': 'Community Moderation',
  'loyalty-program': 'Loyalty Program',
  'audit-logs': 'System Audit Logs',
  'background-jobs': 'Jobs Dashboard',
}
